title: Alexander Kondratev
description: >-
  Personal website of Alexander Kondratev

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kondratev.dev" # the base hostname & protocol for your site

author: Alexander Kondratev
email: mail@kondratev.dev
username: kondratevdev
logo: /assets/images/avatar.webp
social:
  name: Alexander Kondratev
  links:
    - https://github.com/kondratevdev
    - https://t.me/kondratevdev
    - https://linkedin.com/in/kondratevdev

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
